### ISSUE TITLE
Invalid type for path "maba_webpack.bin.dev_server.executable.0". Expected scalar, but got array.

### ISSUE THREAD

**Issue by Danita** [mariusbalcytis/webpack-bundle#12]
Hi, thanks for this bundle! :smile:, I'm really looking forward to trying it in my app but I'm getting this error when I try to run the devserver with a custom configuration (I need it to run on port 8081):

```
[Symfony\Component\Config\Definition\Exception\InvalidTypeException]
  Invalid type for path "maba_webpack.bin.dev_server.executable.0". Expected scalar, but got array.
```

My config is:

```yml
maba_webpack:
    config:
        path: '%kernel.root_dir%/config/webpack.config.js'
        parameters:
            public_path: 'http://192.168.57.123:8081/compiled/'
    bin:
        dev_server:
            executable:
                - node
                - node_modules/webpack-dev-server/bin/webpack-dev-server.js
            arguments:
                - --port 8081
```

I can seem to find out what I'm doing wrong here. Any ideas?
