### ISSUE TITLE
maba webpack causing tty issue on AWS

### ISSUE THREAD

**Issue by lakhman** [mariusbalcytis/webpack-bundle#23]
I'm using code deploy to deploy an app to AWs, I get a bunch of:

> PHP Warning:  proc_open(/dev/tty): failed to open stream: No such device or address in

I needed this:

```yaml
parameters:
    # Disable TTY in webpack bundle
    maba_webpack.bin.disable_tty: true
```

Please add this to the docs when you get a chance, I found it looking through the test files.

Thanks!
